### ISSUE TITLE
code 429

### ISSUE THREAD

**Issue by Hasokeyk** [ekoseoglu/php-parasut-api-v4#2]
Merhabalar Arkadaşlar,

Ek bir bilgi paylaşmak istiyorum.

Paraşüt kullanırken ard arda sorgu yapınca size 429 codu dönüyor. 

Bu kütüphaneyi kullanıyorsanız size çıktı olarak sadece

```
stdClass Object
(
    [code] => 429
)
```

Dönüyor. 

Kütüphaneyi hazırlayan arkadaş paraşüt dökümanını kullanmış ve dökümanda 429 ile ilgili hiç bir bilgi yok. Yani hazırlayan arkadaşla hak veriyorum. :)

https://apidocs.parasut.com/#operation/listProducts

Bu durumu düzeltmek için şunu yapabilirsiniz.

\vendor\inpinos\php-parasut-api-v4\src\Request.php

Yukarıdaki verdiğim yoldaki dosyada satır 169 - 181 bulun aşağıda kodları gösterdim.

```
case '422':
if (isset($responseData->error))
{
	$return->error_title = null;
	$return->error_message = "Unprocessable Entity: ". $responseData->error;
}
elseif (isset($responseData->errors))
{
	$return->error_title = isset($responseData->errors[0]->title) ? $responseData->errors[0]->title : null;
	$errorDetail = isset($responseData->errors[0]->detail) ? $responseData->errors[0]->detail : null;
	$return->error_message = "Unprocessable Entity: ". $errorDetail;
}
break;
```

Aşağıdaki kodu yukarıdaki kodun altına ekleyin. 

```
case '429':
if (isset($responseData->error))
{
	$return->error_title = null;
	$return->error_message = "Unprocessable Entity: ". $responseData->error;
}
elseif (isset($responseData->errors))
{
	$return->error_title = isset($responseData->errors[0]->title) ? $responseData->errors[0]->title : null;
	$errorDetail = isset($responseData->errors[0]->detail) ? $responseData->errors[0]->detail : null;
	$return->error_message = "Unprocessable Entity: ". $errorDetail;
}
break;
```

daha mantıklı olması açısından dediğim satırları klonlayıp case'e 429 yazmanız daha iyi olur :)

kütüphane geliştiricisinin eklemesi tabi daha uygun olur 👍🏼

**Comment by ekoseoglu** [comment]
Teşekkürler, hata kodu kütüphaneye eklendi.

**Comment by Hasokeyk** [comment]
Ben teşekkür ederim ilginize :)
